### ISSUE TITLE
GN3 card pick heuristics

### ISSUE THREAD

**Issue by davidmartos96** [taw/magic-preconstructed-decks-data#1]
Hello!
It looks like for the new Game Night 2022 (GN3) decks, the algorithm has picked versions from Magic Online cards for some of the cards in the decklists.
For example "Elvish Visionary" from the "Boundless Elves" deck.
I know the official printings for the cards are not out yet so it's not possible to predict which one of those will end up being, but it's possible that the heuristics could be improved to exclude certain sets or pick the latest non promo/non online printing of each card.

I would love to help, but I don't have any experience with Ruby

**Comment by taw** [comment]
GN3 needs proper data in mtgjson. Current printings are just a placeholder.

There will be GN3-symbol reprint cards, [just like there were GN2-symbol cards](https://mtg.wtf/card?q=e%3Agn2). The spoiler cards we have even say "X/136".

There's no need for any special code, we're just waiting for mtgjson to finish GN3 data.

**Comment by davidmartos96** [comment]
I see, sorry for the confusion.
I just thought the heuristics were different and that for cards like Elvish Visionary it would have chosen, for instance, the Commander Legends printing before a MTGO one.
Thanks!

**Comment by taw** [comment]
GN3 done.
